name: Build and Distribute

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      
      
      # 清除 Xcode 缓存
      - name: Clean Xcode Cache
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ~/Library/Developer/Xcode/iOS\ DeviceSupport
          rm -rf ~/Library/Developer/Xcode/Archives
          rm -rf ~/Library/Developer/Xcode/Products
          
      # 添加详细的环境信息调试步骤
      - name: Print Environment Info
        run: |
          echo "============= Environment Variables ============="
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "Current Directory: $(pwd)"
          ls -la
          
      # 打印 Xcode 版本信息
      - name: Print Xcode Version
        run: |
          xcodebuild -version
          echo "Xcode Path: $(xcode-select -p)"
          swift --version
    
      # List available schemes
      - name: List Schemes
        run: |
          xcodebuild -list -workspace AIRun/AIRun.xcworkspace
          
      # Build iOS app
      - name: Build iOS App
        env:
          CERTIFICATE_BASE64: ${{ your certificate base64 }}
          CERTIFICATE_PASSWORD: ${{ your certificate password }}
          PROVISIONING_PROFILE_BASE64: ${{ your provisioning profile base64 }}
          KEYCHAIN_PASSWORD: ${{ your keychain password }}
        run: |
          # Make sure we're in the right directory
          cd $GITHUB_WORKSPACE
          
          # Clean the workspace first
          xcodebuild clean -workspace AIRun/AIRun.xcworkspace -scheme AIRun
          
          # Build and archive
          xcodebuild -workspace AIRun/AIRun.xcworkspace \
            -scheme AIRun \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath build/AIRun/archive/AIRun.xcarchive \
            clean archive
          
          xcodebuild -exportArchive \
            -archivePath build/AIRun/archive/AIRun.xcarchive \
            -exportOptionsPlist AIRun/ExportOptions.plist \
            -exportPath build/AIRun/ipa \
            -allowProvisioningUpdates
            
      # # 添加检查步骤
      - name: 检查构建文件
        run: |
           echo "检查 build/AIRun/ipa 目录内容："
           ls -la build/AIRun/ipa/
           echo "检查 build/AIRun 目录内容："
           ls -la build/AIRun/
      
      - name: Archive IPA
        uses: actions/upload-artifact@v4
        with:
          name: release-ipa
          path: build/AIRun/ipa

      - name: Upload to App Store using altool
        env:
          IPA_PATH: "build/AIRun/ipa/ai_oversea.ipa"
          APPLE_ID: "pjmmh6jbh@hotmail.com"
          APP_SPECIFIC_PASSWORD: "jjpl-sliy-dcxy-kgus"
        run: |
          xcrun altool --upload-app -f "$IPA_PATH" \
            -t ios \
            -u "$APPLE_ID" \
            -p "$APP_SPECIFIC_PASSWORD" \
            --verbose
